// Local fallback dataset used only when the backend is unreachable, so the
// workbench always has data to display during a demo. The live backend is the
// source of truth; this mirrors the seeded records.

export const FALLBACK_APPLICATIONS = [
  {
    "id": 3,
    "applicantName": "Amit Patel",
    "age": 19,
    "annualIncome": 150000.0,
    "employmentType": "STUDENT",
    "mobileUsageScore": 40,
    "transactionBehaviorScore": 35,
    "socialSignalScore": 30,
    "creditDecision": "PENDING",
    "confidenceScore": 65,
    "reasoning": "Thin-file applicant; human review is recommended.",
    "fraudRisk": "MEDIUM",
    "reviewStatus": "PENDING_REVIEW",
    "reviewerNotes": null,
    "documentPath": null,
    "createdAt": "2026-08-20T18:59:36.930+00:00"
  },
  {
    "id": 4,
    "applicantName": "Sneha Reddy",
    "age": 28,
    "annualIncome": 400000.0,
    "employmentType": "SELF_EMPLOYED",
    "mobileUsageScore": 75,
    "transactionBehaviorScore": 70,
    "socialSignalScore": 65,
    "creditDecision": "APPROVED",
    "confidenceScore": 76,
    "reasoning": "Consistent alternative-data signals support approval.",
    "fraudRisk": "LOW",
    "reviewStatus": "REVIEWED",
    "reviewerNotes": null,
    "documentPath": null,
    "createdAt": "2026-08-20T18:59:36.930+00:00"
  },
  {
    "id": 5,
    "applicantName": "Vikram Singh",
    "age": 45,
    "annualIncome": 1200000.0,
    "employmentType": "SALARIED",
    "mobileUsageScore": 50,
    "transactionBehaviorScore": 40,
    "socialSignalScore": 45,
    "creditDecision": "PENDING",
    "confidenceScore": 65,
    "reasoning": "Signals are inconclusive; route to a human underwriter.",
    "fraudRisk": "MEDIUM",
    "reviewStatus": "PENDING_REVIEW",
    "reviewerNotes": null,
    "documentPath": null,
    "createdAt": "2026-08-20T18:59:36.931+00:00"
  },
  {
    "id": 6,
    "applicantName": "Demo Ravi Kumar",
    "age": 22,
    "annualIncome": 300000.0,
    "employmentType": "SALARIED",
    "mobileUsageScore": 85,
    "transactionBehaviorScore": 80,
    "socialSignalScore": 70,
    "creditDecision": "APPROVED",
    "confidenceScore": 76,
    "reasoning": "Moderate alternative data indicators suggest manageable risk. Recommend standard credit limit with monitoring.",
    "fraudRisk": "LOW",
    "reviewStatus": "REVIEWED",
    "reviewerNotes": null,
    "documentPath": null,
    "createdAt": "2026-08-20T19:02:38.111+00:00"
  },
  {
    "id": 8,
    "applicantName": "Demo Ravi Kumar",
    "age": 33,
    "annualIncome": 45000.0,
    "employmentType": "SALARIED",
    "mobileUsageScore": 100,
    "transactionBehaviorScore": 46,
    "socialSignalScore": 43,
    "creditDecision": "APPROVED",
    "confidenceScore": 76,
    "reasoning": "Moderate alternative data indicators suggest manageable risk. Recommend standard credit limit with monitoring.",
    "fraudRisk": "LOW",
    "reviewStatus": "AUTO_APPROVED",
    "reviewerNotes": null,
    "documentPath": null,
    "createdAt": "2026-08-20T19:32:40.210+00:00"
  },
  {
    "id": 7,
    "applicantName": "Pipeline Demo",
    "age": 22,
    "annualIncome": 300000.0,
    "employmentType": "GIG_WORKER",
    "mobileUsageScore": 85,
    "transactionBehaviorScore": 80,
    "socialSignalScore": 70,
    "creditDecision": "APPROVED",
    "confidenceScore": 76,
    "reasoning": "Moderate alternative data indicators suggest manageable risk. Recommend standard credit limit with monitoring.",
    "fraudRisk": "LOW",
    "reviewStatus": "REVIEWED",
    "reviewerNotes": "Manual QA review completed",
    "documentPath": null,
    "createdAt": "2026-08-20T19:30:16.420+00:00"
  },
  {
    "id": 9,
    "applicantName": "Demo Ravi Kumar",
    "age": 66,
    "annualIncome": 75888.0,
    "employmentType": "SALARIED",
    "mobileUsageScore": 68,
    "transactionBehaviorScore": 78,
    "socialSignalScore": 7,
    "creditDecision": "APPROVED",
    "confidenceScore": 65,
    "reasoning": "Alternative data is inconclusive. Recommend human underwriter review for final decision.",
    "fraudRisk": "MEDIUM",
    "reviewStatus": "REVIEWED",
    "reviewerNotes": "Manual reviewer workflow check",
    "documentPath": null,
    "createdAt": "2026-08-20T19:44:25.554+00:00"
  },
  {
    "id": 1,
    "applicantName": "Ravi Kumar",
    "age": 22,
    "annualIncome": 300000.0,
    "employmentType": "GIG_WORKER",
    "mobileUsageScore": 85,
    "transactionBehaviorScore": 80,
    "socialSignalScore": 70,
    "creditDecision": "APPROVED",
    "confidenceScore": 76,
    "reasoning": "Strong alternative data profile for a new-to-credit gig worker.",
    "fraudRisk": "LOW",
    "reviewStatus": "REVIEWED",
    "reviewerNotes": null,
    "documentPath": "uploads/1-df28b597-8168-44ae-a280-7e788453ef07-sample-income-evidence.txt",
    "createdAt": "2026-08-20T18:59:36.921+00:00"
  },
  {
    "id": 10,
    "applicantName": "Ravi Kumar",
    "age": 28,
    "annualIncome": 300000.0,
    "employmentType": "SALARIED",
    "mobileUsageScore": 65,
    "transactionBehaviorScore": 70,
    "socialSignalScore": 55,
    "creditDecision": "APPROVED",
    "confidenceScore": 76,
    "reasoning": "Moderate alternative data indicators suggest manageable risk. Recommend standard credit limit with monitoring.",
    "fraudRisk": "LOW",
    "reviewStatus": "AUTO_APPROVED",
    "reviewerNotes": null,
    "documentPath": null,
    "createdAt": "2026-08-21T01:53:00.769+00:00"
  },
  {
    "id": 11,
    "applicantName": "Demo Applicant",
    "age": 29,
    "annualIncome": 480000.0,
    "employmentType": "GIG_WORKER",
    "mobileUsageScore": 85,
    "transactionBehaviorScore": 80,
    "socialSignalScore": 70,
    "creditDecision": "APPROVED",
    "confidenceScore": 88,
    "reasoning": "Strong alternative data profile with consistent mobile engagement and healthy transaction behavior. Income stability supports creditworthiness.",
    "fraudRisk": "LOW",
    "reviewStatus": "AUTO_APPROVED",
    "reviewerNotes": null,
    "documentPath": null,
    "createdAt": "2026-08-21T03:18:09.988+00:00"
  },
  {
    "id": 12,
    "applicantName": "Demo Review Applicant",
    "age": 19,
    "annualIncome": 180000.0,
    "employmentType": "STUDENT",
    "mobileUsageScore": 20,
    "transactionBehaviorScore": 45,
    "socialSignalScore": 50,
    "creditDecision": "PENDING",
    "confidenceScore": 60,
    "reasoning": "Low alternative data scores indicate insufficient financial track record. Mobile usage and transaction patterns fall below risk thresholds. [BIAS GUARDRAIL: Age-based rejection escalated to human review.]",
    "fraudRisk": "HIGH",
    "reviewStatus": "PENDING_REVIEW",
    "reviewerNotes": null,
    "documentPath": null,
    "createdAt": "2026-08-21T03:18:25.086+00:00"
  },
  {
    "id": 13,
    "applicantName": "Demo Review Applicant",
    "age": 19,
    "annualIncome": 180000.0,
    "employmentType": "STUDENT",
    "mobileUsageScore": 20,
    "transactionBehaviorScore": 45,
    "socialSignalScore": 50,
    "creditDecision": "APPROVED",
    "confidenceScore": 60,
    "reasoning": "Low alternative data scores indicate insufficient financial track record. Mobile usage and transaction patterns fall below risk thresholds. [BIAS GUARDRAIL: Age-based rejection escalated to human review.]",
    "fraudRisk": "HIGH",
    "reviewStatus": "REVIEWED",
    "reviewerNotes": "Demo reviewer verified supporting context.",
    "documentPath": "uploads/13-97e65f5c-028e-4a9a-9aeb-5231613e2bd8-demo-evidence.txt",
    "createdAt": "2026-08-21T03:20:25.985+00:00"
  },
  {
    "id": 2,
    "applicantName": "Priya Sharma",
    "age": 35,
    "annualIncome": 800000.0,
    "employmentType": "SALARIED",
    "mobileUsageScore": 20,
    "transactionBehaviorScore": 45,
    "socialSignalScore": 50,
    "creditDecision": "APPROVED",
    "confidenceScore": 92,
    "reasoning": "Low mobile usage score indicates a possible fraud pattern requiring review.",
    "fraudRisk": "HIGH",
    "reviewStatus": "REVIEWED",
    "reviewerNotes": "Reviewer finalised approved in the NexCredit workbench.",
    "documentPath": null,
    "createdAt": "2026-08-20T18:59:36.929+00:00"
  }
];

export const FALLBACK_AUDIT_LOGS = [
  {
    "id": 12,
    "applicationId": 2,
    "decision": "APPROVED",
    "reasoning": "Human review completed: Reviewer finalised approved in the NexCredit workbench.",
    "timestamp": "2026-08-21T03:48:27.362+00:00"
  },
  {
    "id": 11,
    "applicationId": 13,
    "decision": "APPROVED",
    "reasoning": "Human review completed: Demo reviewer verified supporting context.",
    "timestamp": "2026-08-21T03:20:26.457+00:00"
  },
  {
    "id": 10,
    "applicationId": 13,
    "decision": "PENDING",
    "reasoning": "Low alternative data scores indicate insufficient financial track record. Mobile usage and transaction patterns fall below risk thresholds. [BIAS GUARDRAIL: Age-based rejection escalated to human review.]",
    "timestamp": "2026-08-21T03:20:26.040+00:00"
  },
  {
    "id": 9,
    "applicationId": 12,
    "decision": "PENDING",
    "reasoning": "Low alternative data scores indicate insufficient financial track record. Mobile usage and transaction patterns fall below risk thresholds. [BIAS GUARDRAIL: Age-based rejection escalated to human review.]",
    "timestamp": "2026-08-21T03:18:25.137+00:00"
  },
  {
    "id": 8,
    "applicationId": 11,
    "decision": "APPROVED",
    "reasoning": "Strong alternative data profile with consistent mobile engagement and healthy transaction behavior. Income stability supports creditworthiness.",
    "timestamp": "2026-08-21T03:18:10.060+00:00"
  },
  {
    "id": 7,
    "applicationId": 10,
    "decision": "APPROVED",
    "reasoning": "Moderate alternative data indicators suggest manageable risk. Recommend standard credit limit with monitoring.",
    "timestamp": "2026-08-21T01:53:00.818+00:00"
  },
  {
    "id": 6,
    "applicationId": 9,
    "decision": "APPROVED",
    "reasoning": "Human review completed: Manual reviewer workflow check",
    "timestamp": "2026-08-20T20:05:31.173+00:00"
  },
  {
    "id": 5,
    "applicationId": 9,
    "decision": "PENDING",
    "reasoning": "Alternative data is inconclusive. Recommend human underwriter review for final decision.",
    "timestamp": "2026-08-20T19:44:25.621+00:00"
  },
  {
    "id": 4,
    "applicationId": 8,
    "decision": "APPROVED",
    "reasoning": "Moderate alternative data indicators suggest manageable risk. Recommend standard credit limit with monitoring.",
    "timestamp": "2026-08-20T19:32:40.269+00:00"
  },
  {
    "id": 3,
    "applicationId": 7,
    "decision": "APPROVED",
    "reasoning": "Moderate alternative data indicators suggest manageable risk. Recommend standard credit limit with monitoring.",
    "timestamp": "2026-08-20T19:30:16.454+00:00"
  },
  {
    "id": 2,
    "applicationId": null,
    "decision": "APPROVED",
    "reasoning": "Moderate alternative data indicators suggest manageable risk. Recommend standard credit limit with monitoring.",
    "timestamp": "2026-08-20T19:02:37.866+00:00"
  },
  {
    "id": 1,
    "applicationId": null,
    "decision": "APPROVED",
    "reasoning": "Moderate alternative data indicators suggest manageable risk. Recommend standard credit limit with monitoring.",
    "timestamp": "2026-08-20T19:00:40.101+00:00"
  }
];
